// This file is generated by modules/charset/invisible/generate.go DO NOT EDIT
// Copyright (C) Kumo inc. and its affiliates.
// Author: Jeff.li lijippy@163.com
// All rights reserved.
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

package charset

import "unicode"

var InvisibleRanges = &unicode.RangeTable{
	R16: []unicode.Range16{
		{Lo: 11, Hi: 13, Stride: 1},
		{Lo: 127, Hi: 160, Stride: 33},
		{Lo: 173, Hi: 847, Stride: 674},
		{Lo: 1564, Hi: 4447, Stride: 2883},
		{Lo: 4448, Hi: 6068, Stride: 1620},
		{Lo: 6069, Hi: 6155, Stride: 86},
		{Lo: 6156, Hi: 6158, Stride: 1},
		{Lo: 7355, Hi: 7356, Stride: 1},
		{Lo: 8192, Hi: 8207, Stride: 1},
		{Lo: 8234, Hi: 8239, Stride: 1},
		{Lo: 8287, Hi: 8303, Stride: 1},
		{Lo: 10240, Hi: 12288, Stride: 2048},
		{Lo: 12644, Hi: 65024, Stride: 52380},
		{Lo: 65025, Hi: 65039, Stride: 1},
		{Lo: 65279, Hi: 65440, Stride: 161},
		{Lo: 65520, Hi: 65528, Stride: 1},
		{Lo: 65532, Hi: 65532, Stride: 1},
	},
	R32: []unicode.Range32{
		{Lo: 78844, Hi: 119155, Stride: 40311},
		{Lo: 119156, Hi: 119162, Stride: 1},
		{Lo: 917504, Hi: 917631, Stride: 1},
		{Lo: 917760, Hi: 917999, Stride: 1},
	},
	LatinOffset: 2,
}
