#!/bin/bash

#############################################################################
# This script sets some defaults for kmup to run in a FHS compliant manner #
#############################################################################

# It assumes that you place this script as kmup in /usr/bin
#
# And place the original in /usr/lib/kmup with working files in /var/lib/kmup
# and main configuration in /etc/kmup/app.ini
KMUP="/usr/lib/kumose/kmup"
WORK_DIR="/var/lib/kmup"
APP_INI="/etc/kmup/app.ini"

APP_INI_SET=""
for i in "$@"; do
	case "$i" in
	"-c")
		APP_INI_SET=1
		;;
	"-c="*)
		APP_INI_SET=1
		;;
	"--config")
		APP_INI_SET=1
		;;
	"--config="*)
		APP_INI_SET=1
		;;
	*)
	;;
	esac
done

if [ -z "$APP_INI_SET" ]; then
	CONF_ARG=("-c" "${KMUP_APP_INI:-$APP_INI}")
fi

# Provide FHS compliant defaults
KMUP_WORK_DIR="${KMUP_WORK_DIR:-$WORK_DIR}" exec -a "$0" "$KMUP" "${CONF_ARG[@]}"  "$@"
